@extends('kpbu')

@section('content-kpbu')
    <h5><b>Bagaimana skema pengembalian investasi KPBU ?</b></h5><br>
    <p style="text-align: justify;">Pengembalian investasi bagi Badan Usaha Pelaksana meliputi penutupan biaya modal, biaya operasional, dan keuntungan yang wajar. Pada KPBU Indonesia terdapat tiga (3) jenis pengembalian investasi, yaitu:</p>
    <p>a. Pembayaran dalam bentuk tarif oleh pengguna</p>
    <p style="padding-left: 14px; text-align: justify;">Pada skema tarif, Badan Usaha Pelaksana mendapatkan pengembalian investasi secara langsung dari masyarakat pengguna layanan infrastruktur. Semisal infrastruktur jalan tol yang masyarakat membayarkan tarif tol atas layanan yang digunakan setelah Badan Usaha membangun, mengoperasikan, dan memelihara selama masa kerjasama. Besaran tarif ditetapkan oleh pemerintah, dan dimungkinkan adanya penyesuaian. Hal yang perlu dipastikan adalah tersedianya permintaan (demand) dari pengguna proyek.</p>
    <p>b. Pembayaran ketersediaan layanan oleh PJPK</p>
    <p style="padding-left: 14px; text-align: justify;">Pembayaran ketersediaan layanan (availability payment/AP) merupakan pengembalian investasi yang dananya bersumber dari anggaran pemerintah (APBN atau APBD). Skema ini sesuai untuk jenis infrastruktur yang memiliki sedikit atau tidak ada pendapatan, semisal sektor kesehatan (subsektor: rumah sakit), pemasyarakatan, konservasi energi (subsektor: penerangan jalan umum), dan lain-lain. Pembayaran dilakukan secara berkala oleh PJPK kepada BUP atas tersedianyan layanan sesuai kriteria (kuantitas dan/atau kualitas) sebagaimana ditentukan pada perjanjian kerjasama, yang jika tidak dipenuhi dapat dikenakan penalti. Hal yang perlu diperhatikan terkait kapasitas fiskal PJPK.</p>
    <p>c. Bentuk lain sepanjang tidak bertentangan dengan peraturan perundang-undangan</p>
    <p style="padding-left: 14px; text-align: justify;">Pengembalian investasi bentuk lain dapat digunakan sendiri atau dikombinasikan dengan pengembalian investasi availability payment untuk sektor-sektor infrastruktur yang secara bawaan tidak bisa didapatkan penghasilan (revenue). Salah satu bentuk lain pengembalian investasi adalah penyatuan (bundling) aspek infrastruktur umum dengan aspek komersial, semisal proyek KPBU sektor perkeretapian yang disatukan dengan pembangunan kawasan properti. Sebagai contoh yang tidak bisa diimplementasikan adalah infrastruktur penerangan jalan umum yang pada tiang-tiangnya ditambatkan reklame iklan. Gagasan tersebut tidak dapat dilakukan karena terdapat regulasi yang melarang pemasangan reklame iklan pada tiang PJU berkaitan dengan keamanan pengguna jalan.</p>
@endsection